version: "3.9"
   
services:
  web:
    container_name: django
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DB_HOST=${DB_HOST}
      - DJANGO_SUPERUSER_USERNAME=${SUPERUSER}
      - DJANGO_SUPERUSER_PASSWORD=${SUPERUSER_PASS}
      - DJANGO_SUPERUSER_EMAIL=${SUPERUSER_EMAIL}
    volumes:
      - ./static:/usr/src/app/static
    networks:
      - djangonetwork
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:${PG_VERSION}-alpine
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - djangonetwork

  nginx:
    container_name: nginx
    image: nginx:${NGINX_VERSION}-alpine
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
      - ./static:/data/static
    depends_on:
      - web
    ports:
      - "80:80"
    networks:
      - djangonetwork

networks:
      djangonetwork:
          driver: bridge
